name: Unzip File

on:
  push:
    paths:
      - '**/*.zip'  # Detecta qualquer arquivo .zip enviado para o repositório

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Unzip file
        run: unzip path/to/your/file.zip -d path/to/extract/directory
