name: Unzip File

on:
  push:
    paths:
      - '**/*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: ls -l

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Create extraction directory
        run: mkdir -p ./extracted_files

      - name: Unzip file(s)
        run: unzip '**/*.zip' -d ./extracted_files
